---
- name: Create user1 and set up SSH key
  hosts: target_server
  become: true
  vars_files:
    - vault.yml  # Файл, содержащий зашифрованный SSH-ключ

  tasks:
    - name: Create user1
      user:
        name: user1
        shell: /bin/bash
        create_home: yes

    - name: Ensure .ssh directory exists
      file:
        path: /home/user1/.ssh
        state: directory
        owner: user1
        group: user1
        mode: '0700'

    - name: Generate SSH key pair for user1
      command: ssh-keygen -t rsa -b 4096 -f /home/user1/.ssh/id_rsa -N ""
      args:
        creates: /home/user1/.ssh/id_rsa
      become: true
      become_user: root

    - name: Read generated public key
      command: cat /home/user1/.ssh/id_rsa.pub
      register: ssh_key_output
      changed_when: false

    - name: Store generated public key in vault variable
      set_fact:
        ssh_public_key: "{{ ssh_key_output.stdout }}"

    - name: Deploy SSH public key
      copy:
        content: "{{ ssh_public_key }}"
        dest: /home/user1/.ssh/authorized_keys
        owner: user1
        group: user1
        mode: '0600'
