---
- name: Установка и настройка MySQL
  hosts: localhost
  become: yes
  tasks:

    - name: Обновление кеша пакетов (для Debian-based систем)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Установка MySQL-сервера (Ubuntu/Debian)
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Установка MySQL-сервера (CentOS/RHEL)
      yum:
        name: mysql-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Запуск и включение MySQL в автозапуск
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Установка root-пароля MySQL
      mysql_user:
        name: root
        host: localhost
        password: "SuperSecretPass"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      ignore_errors: yes

    - name: Создание тестовой базы данных
      mysql_db:
        name: test_db
        state: present
        login_user: root
        login_password: "SuperSecretPass"
